export const USER = {
  LIST: {
    PROGRESS: 'USER_LIST_PROGRESS',
    RESULT: 'USER_LIST_RESULT',
    PAGINATION: {
      UPDATE: {
        NEXT: 'USER_LIST_PAGINATION_UPDATE_NEXT'
      }
    }
  },
  DETAIL: {
    PROGRESS: 'USER_DETAIL_PROGRESS',
    RESULT: 'USER_DETAIL_RESULT'
  }
};